apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-app
spec:
  replicas: 2  # Increased replicas for redundancy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: llm-app
  template:
    metadata:
      labels:
        app: llm-app
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: llm-app
        image: llmregistrymanoj123.azurecr.io/llm-app:v1
        ports:
        - containerPort: 5000  # FIXED: Matching Flask app port
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: llm-app-service
spec:
  selector:
    app: llm-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # FIXED: Matching Flask app port
  type: LoadBalancer
