name: Deploy LLM to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login myacr.azurecr.io -u myacr --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t myacr.azurecr.io/llm-app:latest .
          docker push myacr.azurecr.io/llm-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Deploy to AKS
        run: |
          kubectl apply -f llm-deployment.yaml
          kubectl rollout status deployment llm-app
